<a href="https://colab.research.google.com/github/LucasFaleirosMoreira/university-studies/blob/main/IA_30_08_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import math

In [ ]:
df_teste = pd.read_csv("/teste.csv", sep=';')
df_treino = pd.read_excel("/treino.xlsx")

In [ ]:
df_teste.head()

   height  weight  sex_bool     sex
0  159.96   67.67         0  Female
1  165.80   91.29         1    Male
2  185.48   52.25         0  Female
3  168.15   67.73         0  Female
4  165.98   51.98         0  Female

In [ ]:
df_treino.head()

   height  weight  sex_bool   sex
0  172.08   73.84         1  Male
1  148.45   88.52         1  Male
2  178.46   81.11         1  Male
3  171.04   87.56         1  Male
4  172.11  101.16         1  Male

In [ ]:
# Função para calcular a distância euclidiana
def distancia_euclidiana(p1, p2):
    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)

# Lista para armazenar as distâncias
distancias = []

# Iterando pelas linhas dos DataFrames
for _, amostra_treino in df_treino.iterrows():
    for _, amostra_teste in df_teste.iterrows():
        # Calculando a distância entre 'height' e 'weight'
        distancia = distancia_euclidiana([amostra_treino['height'], amostra_treino['weight']],
                                        [amostra_teste['height'], amostra_teste['weight']])
        distancias.append((distancia, amostra_treino[['height', 'weight']], amostra_teste[['height', 'weight']]))

# Exibindo as distâncias e as amostras
for dist in distancias:
    print(f"Distância: {dist[0]:.2f}, Amostra Treinamento: {dist[1].values}, Amostra Teste: {dist[2].values}")

Distância: 13.60, Amostra Treinamento: [172.08 73.84], Amostra Teste: [159.96 67.67]
Distância: 18.55, Amostra Treinamento: [172.08 73.84], Amostra Teste: [165.8 91.29]
Distância: 25.41, Amostra Treinamento: [172.08 73.84], Amostra Teste: [185.48 52.25]
Distância: 7.26, Amostra Treinamento: [172.08 73.84], Amostra Teste: [168.15 67.73]
Distância: 22.70, Amostra Treinamento: [172.08 73.84], Amostra Teste: [165.98 51.98]
Distância: 13.70, Amostra Treinamento: [172.08 73.84], Amostra Teste: [185.42 70.74]
Distância: 11.88, Amostra Treinamento: [172.08 73.84], Amostra Teste: [160.2 74.05]
Distância: 0.51, Amostra Treinamento: [172.08 73.84], Amostra Teste: [172.58 73.92]
Distância: 23.14, Amostra Treinamento: [172.08 73.84], Amostra Teste: [167.33 51.19]
Distância: 17.44, Amostra Treinamento: [172.08 73.84], Amostra Teste: [160.05 86.46]
Distância: 24.18, Amostra Treinamento: [172.08 73.84], Amostra Teste: [156.83 55.07]
Distância: 9.56, Amostra Treinamento: [172.08 73.84], Amostra Teste: [163.71 69.23]
Distância: 11.80, Amostra Treinamento: [172.08 73.84], Amostra Teste: [160.73 77.07]
Distância: 8.76, Amostra Treinamento: [172.08 73.84], Amostra Teste: [164.96 68.74]
Distância: 9.59, Amostra Treinamento: [172.08 73.84], Amostra Teste: [180.01 68.44]
Distância: 17.94, Amostra Treinamento: [172.08 73.84], Amostra Teste: [168.11 56.34]
Distância: 8.63, Amostra Treinamento: [172.08 73.84], Amostra Teste: [177.57 80.5]
Distância: 7.56, Amostra Treinamento: [172.08 73.84], Amostra Teste: [178.15 78.35]
Distância: 17.28, Amostra Treinamento: [172.08 73.84], Amostra Teste: [188.72 78.51]
Distância: 23.12, Amostra Treinamento: [172.08 73.84], Amostra Teste: [174.55 50.85]
Distância: 0.75, Amostra Treinamento: [172.08 73.84], Amostra Teste: [171.91 74.57]
Distância: 15.45, Amostra Treinamento: [172.08 73.84], Amostra Teste: [172.05 58.39]
Distância: 18.71, Amostra Treinamento: [172.08 73.84], Amostra Teste: [172.43 92.55]
Distância: 2.19, Amostra Treinamento: [172.08 73.84], Amostra Teste: [171.32 75.89]
Distância: 16.42, Amostra Treinamento: [172.08 73.84], Amostra Teste: [187.74 68.89]
Distância: 23.82, Amostra Treinamento: [148.45 88.52], Amostra Teste: [159.96 67.67]
Distância: 17.57, Amostra Treinamento: [148.45 88.52], Amostra Teste: [165.8 91.29]
Distância: 51.83, Amostra Treinamento: [148.45 88.52], Amostra Teste: [185.48 52.25]
Distância: 28.64, Amostra Treinamento: [148.45 88.52], Amostra Teste: [168.15 67.73]
Distância: 40.53, Amostra Treinamento: [148.45 88.52], Amostra Teste: [165.98 51.98]
Distância: 41.02, Amostra Treinamento: [148.45 88.52], Amostra Teste: [185.42 70.74]
Distância: 18.64, Amostra Treinamento: [148.45 88.52], Amostra Teste: [160.2 74.05]
Distância: 28.20, Amostra Treinamento: [148.45 88.52], Amostra Teste: [172.58 73.92]
Distância: 41.83, Amostra Treinamento: [148.45 88.52], Amostra Teste: [167.33 51.19]
Distância: 11.78, Amostra Treinamento: [148.45 88.52], Amostra Teste: [160.05 86.46]
Distância: 34.48, Amostra Treinamento: [148.45 88.52], Amostra Teste: [156.83 55.07]
Distância: 24.60, Amostra Treinamento: [148.45 88.52], Amostra Teste: [163.71 69.23]
Distância: 16.79, Amostra Treinamento: [148.45 88.52], Amostra Teste: [160.73 77.07]
Distância: 25.76, Amostra Treinamento: [148.45 88.52], Amostra Teste: [164.96 68.74]
Distância: 37.41, Amostra Treinamento: [148.45 88.52], Amostra Teste: [180.01 68.44]
Distância: 37.71, Amostra Treinamento: [148.45 88.52], Amostra Teste: [168.11 56.34]
Distância: 30.20, Amostra Treinamento: [148.45 88.52], Amostra Teste: [177.57 80.5]
Distância: 31.39, Amostra Treinamento: [148.45 88.52], Amostra Teste: [178.15 78.35]
Distância: 41.50, Amostra Treinamento: [148.45 88.52], Amostra Teste: [188.72 78.51]
Distância: 45.83, Amostra Treinamento: [148.45 88.52], Amostra Teste: [174.55 50.85]
Distância: 27.29, Amostra Treinamento: [148.45 88.52], Amostra Teste: [171.91 74.57]
Distância: 38.27, Amostra Treinamento: [148.45 88.52], Amostra Teste: [172.05 58.39]
Distância: 24.32, Amostra Treinamento: [148.45 88.52], Amostra Teste: [172.43 92.55]
Distância: 26.13, Amostra Treinamento: [148.45 88.52], Amostra Teste: [171.32 75.89]
Distância: 43.92, Amostra Treinamento: [148.45 88.52], Amostra Teste: [187.74 68.89]
Distância: 22.87, Amostra Treinamento: [178.46 81.11], Amostra Teste: [159.96 67.67]
Distância: 16.25, Amostra Treinamento: [178.46 81.11], Amostra Teste: [165.8 91.29]
Distância: 29.70, Amostra Treinamento: [178.46 81.11], Amostra Teste: [185.48 52.25]
Distância: 16.89, Amostra Treinamento: [178.46 81.11], Amostra Teste: [168.15 67.73]
Distância: 31.69, Amostra Treinamento: [178.46 81.11], Amostra Teste: [165.98 51.98]
Distância: 12.49, Amostra Treinamento: [178.46 81.11], Amostra Teste: [185.42 70.74]
Distância: 19.58, Amostra Treinamento: [178.46 81.11], Amostra Teste: [160.2 74.05]
Distância: 9.29, Amostra Treinamento: [178.46 81.11], Amostra Teste: [172.58 73.92]
Distância: 31.92, Amostra Treinamento: [178.46 81.11], Amostra Teste: [167.33 51.19]
Distância: 19.17, Amostra Treinamento: [178.46 81.11], Amostra Teste: [160.05 86.46]
Distância: 33.85, Amostra Treinamento: [178.46 81.11], Amostra Teste: [156.83 55.07]
Distância: 18.94, Amostra Treinamento: [178.46 81.11], Amostra Teste: [163.71 69.23]
Distância: 18.18, Amostra Treinamento: [178.46 81.11], Amostra Teste: [160.73 77.07]
Distância: 18.31, Amostra Treinamento: [178.46 81.11], Amostra Teste: [164.96 68.74]
Distância: 12.76, Amostra Treinamento: [178.46 81.11], Amostra Teste: [180.01 68.44]
Distância: 26.85, Amostra Treinamento: [178.46 81.11], Amostra Teste: [168.11 56.34]
Distância: 1.08, Amostra Treinamento: [178.46 81.11], Amostra Teste: [177.57 80.5]
Distância: 2.78, Amostra Treinamento: [178.46 81.11], Amostra Teste: [178.15 78.35]
Distância: 10.58, Amostra Treinamento: [178.46 81.11], Amostra Teste: [188.72 78.51]
Distância: 30.51, Amostra Treinamento: [178.46 81.11], Amostra Teste: [174.55 50.85]
Distância: 9.26, Amostra Treinamento: [178.46 81.11], Amostra Teste: [171.91 74.57]
Distância: 23.61, Amostra Treinamento: [178.46 81.11], Amostra Teste: [172.05 58.39]
Distância: 12.93, Amostra Treinamento: [178.46 81.11], Amostra Teste: [172.43 92.55]
Distância: 8.84, Amostra Treinamento: [178.46 81.11], Amostra Teste: [171.32 75.89]
Distância: 15.34, Amostra Treinamento: [178.46 81.11], Amostra Teste: [187.74 68.89]
Distância: 22.77, Amostra Treinamento: [171.04 87.56], Amostra Teste: [159.96 67.67]
Distância: 6.43, Amostra Treinamento: [171.04 87.56], Amostra Teste: [165.8 91.29]
Distância: 38.15, Amostra Treinamento: [171.04 87.56], Amostra Teste: [185.48 52.25]
Distância: 20.04, Amostra Treinamento: [171.04 87.56], Amostra Teste: [168.15 67.73]
Distância: 35.94, Amostra Treinamento: [171.04 87.56], Amostra Teste: [165.98 51.98]
Distância: 22.13, Amostra Treinamento: [171.04 87.56], Amostra Teste: [185.42 70.74]
Distância: 17.32, Amostra Treinamento: [171.04 87.56], Amostra Teste: [160.2 74.05]
Distância: 13.73, Amostra Treinamento: [171.04 87.56], Amostra Teste: [172.58 73.92]
Distância: 36.56, Amostra Treinamento: [171.04 87.56], Amostra Teste: [167.33 51.19]
Distância: 11.04, Amostra Treinamento: [171.04 87.56], Amostra Teste: [160.05 86.46]
Distância: 35.46, Amostra Treinamento: [171.04 87.56], Amostra Teste: [156.83 55.07]
Distância: 19.74, Amostra Treinamento: [171.04 87.56], Amostra Teste: [163.71 69.23]
Distância: 14.71, Amostra Treinamento: [171.04 87.56], Amostra Teste: [160.73 77.07]
Distância: 19.78, Amostra Treinamento: [171.04 87.56], Amostra Teste: [164.96 68.74]
Distância: 21.12, Amostra Treinamento: [171.04 87.56], Amostra Teste: [180.01 68.44]
Distância: 31.36, Amostra Treinamento: [171.04 87.56], Amostra Teste: [168.11 56.34]
Distância: 9.62, Amostra Treinamento: [171.04 87.56], Amostra Teste: [177.57 80.5]
Distância: 11.64, Amostra Treinamento: [171.04 87.56], Amostra Teste: [178.15 78.35]
Distância: 19.86, Amostra Treinamento: [171.04 87.56], Amostra Teste: [188.72 78.51]
Distância: 36.88, Amostra Treinamento: [171.04 87.56], Amostra Teste: [174.55 50.85]
Distância: 13.02, Amostra Treinamento: [171.04 87.56], Amostra Teste: [171.91 74.57]
Distância: 29.19, Amostra Treinamento: [171.04 87.56], Amostra Teste: [172.05 58.39]
Distância: 5.18, Amostra Treinamento: [171.04 87.56], Amostra Teste: [172.43 92.55]
Distância: 11.67, Amostra Treinamento: [171.04 87.56], Amostra Teste: [171.32 75.89]
Distância: 25.05, Amostra Treinamento: [171.04 87.56], Amostra Teste: [187.74 68.89]
Distância: 35.63, Amostra Treinamento: [172.11 101.16], Amostra Teste: [159.96 67.67]
Distância: 11.71, Amostra Treinamento: [172.11 101.16], Amostra Teste: [165.8 91.29]
Distância: 50.70, Amostra Treinamento: [172.11 101.16], Amostra Teste: [185.48 52.25]
Distância: 33.66, Amostra Treinamento: [172.11 101.16], Amostra Teste: [168.15 67.73]
Distância: 49.56, Amostra Treinamento: [172.11 101.16], Amostra Teste: [165.98 51.98]
Distância: 33.20, Amostra Treinamento: [172.11 101.16], Amostra Teste: [185.42 70.74]
Distância: 29.61, Amostra Treinamento: [172.11 101.16], Amostra Teste: [160.2 74.05]
Distância: 27.24, Amostra Treinamento: [172.11 101.16], Amostra Teste: [172.58 73.92]
Distância: 50.20, Amostra Treinamento: [172.11 101.16], Amostra Teste: [167.33 51.19]
Distância: 19.01, Amostra Treinamento: [172.11 101.16], Amostra Teste: [160.05 86.46]
Distância: 48.56, Amostra Treinamento: [172.11 101.16], Amostra Teste: [156.83 55.07]
Distância: 33.02, Amostra Treinamento: [172.11 101.16], Amostra Teste: [163.71 69.23]
Distância: 26.64, Amostra Treinamento: [172.11 101.16], Amostra Teste: [160.73 77.07]
Distância: 33.20, Amostra Treinamento: [172.11 101.16], Amostra Teste: [164.96 68.74]
Distância: 33.66, Amostra Treinamento: [172.11 101.16], Amostra Teste: [180.01 68.44]
Distância: 45.00, Amostra Treinamento: [172.11 101.16], Amostra Teste: [168.11 56.34]
Distância: 21.37, Amostra Treinamento: [172.11 101.16], Amostra Teste: [177.57 80.5]
Distância: 23.60, Amostra Treinamento: [172.11 101.16], Amostra Teste: [178.15 78.35]
Distância: 28.09, Amostra Treinamento: [172.11 101.16], Amostra Teste: [188.72 78.51]
Distância: 50.37, Amostra Treinamento: [172.11 101.16], Amostra Teste: [174.55 50.85]
Distância: 26.59, Amostra Treinamento: [172.11 101.16], Amostra Teste: [171.91 74.57]
Distância: 42.77, Amostra Treinamento: [172.11 101.16], Amostra Teste: [172.05 58.39]
Distância: 8.62, Amostra Treinamento: [172.11 101.16], Amostra Teste: [172.43 92.55]
Distância: 25.28, Amostra Treinamento: [172.11 101.16], Amostra Teste: [171.32 75.89]
Distância: 35.86, Amostra Treinamento: [172.11 101.16], Amostra Teste: [187.74 68.89]
Distância: 14.60, Amostra Treinamento: [169.66 56.76], Amostra Teste: [159.96 67.67]
Distância: 34.75, Amostra Treinamento: [169.66 56.76], Amostra Teste: [165.8 91.29]
Distância: 16.45, Amostra Treinamento: [169.66 56.76], Amostra Teste: [185.48 52.25]
Distância: 11.07, Amostra Treinamento: [169.66 56.76], Amostra Teste: [168.15 67.73]
Distância: 6.03, Amostra Treinamento: [169.66 56.76], Amostra Teste: [165.98 51.98]
Distância: 21.07, Amostra Treinamento: [169.66 56.76], Amostra Teste: [185.42 70.74]
Distância: 19.71, Amostra Treinamento: [169.66 56.76], Amostra Teste: [160.2 74.05]
Distância: 17.41, Amostra Treinamento: [169.66 56.76], Amostra Teste: [172.58 73.92]
Distância: 6.04, Amostra Treinamento: [169.66 56.76], Amostra Teste: [167.33 51.19]
Distância: 31.22, Amostra Treinamento: [169.66 56.76], Amostra Teste: [160.05 86.46]
Distância: 12.94, Amostra Treinamento: [169.66 56.76], Amostra Teste: [156.83 55.07]
Distância: 13.82, Amostra Treinamento: [169.66 56.76], Amostra Teste: [163.71 69.23]
Distância: 22.19, Amostra Treinamento: [169.66 56.76], Amostra Teste: [160.73 77.07]
Distância: 12.87, Amostra Treinamento: [169.66 56.76], Amostra Teste: [164.96 68.74]
Distância: 15.61, Amostra Treinamento: [169.66 56.76], Amostra Teste: [180.01 68.44]
Distância: 1.61, Amostra Treinamento: [169.66 56.76], Amostra Teste: [168.11 56.34]
Distância: 25.02, Amostra Treinamento: [169.66 56.76], Amostra Teste: [177.57 80.5]
Distância: 23.20, Amostra Treinamento: [169.66 56.76], Amostra Teste: [178.15 78.35]
Distância: 28.92, Amostra Treinamento: [169.66 56.76], Amostra Teste: [188.72 78.51]
Distância: 7.67, Amostra Treinamento: [169.66 56.76], Amostra Teste: [174.55 50.85]
Distância: 17.95, Amostra Treinamento: [169.66 56.76], Amostra Teste: [171.91 74.57]
Distância: 2.89, Amostra Treinamento: [169.66 56.76], Amostra Teste: [172.05 58.39]
Distância: 35.90, Amostra Treinamento: [169.66 56.76], Amostra Teste: [172.43 92.55]
Distância: 19.20, Amostra Treinamento: [169.66 56.76], Amostra Teste: [171.32 75.89]
Distância: 21.77, Amostra Treinamento: [169.66 56.76], Amostra Teste: [187.74 68.89]
Distância: 15.56, Amostra Treinamento: [172.1 57.94], Amostra Teste: [159.96 67.67]
Distância: 33.94, Amostra Treinamento: [172.1 57.94], Amostra Teste: [165.8 91.29]
Distância: 14.54, Amostra Treinamento: [172.1 57.94], Amostra Teste: [185.48 52.25]
Distância: 10.56, Amostra Treinamento: [172.1 57.94], Amostra Teste: [168.15 67.73]
Distância: 8.54, Amostra Treinamento: [172.1 57.94], Amostra Teste: [165.98 51.98]
Distância: 18.47, Amostra Treinamento: [172.1 57.94], Amostra Teste: [185.42 70.74]
Distância: 20.03, Amostra Treinamento: [172.1 57.94], Amostra Teste: [160.2 74.05]
Distância: 15.99, Amostra Treinamento: [172.1 57.94], Amostra Teste: [172.58 73.92]
Distância: 8.27, Amostra Treinamento: [172.1 57.94], Amostra Teste: [167.33 51.19]
Distância: 30.96, Amostra Treinamento: [172.1 57.94], Amostra Teste: [160.05 86.46]
Distância: 15.54, Amostra Treinamento: [172.1 57.94], Amostra Teste: [156.83 55.07]
Distância: 14.07, Amostra Treinamento: [172.1 57.94], Amostra Teste: [163.71 69.23]
Distância: 22.25, Amostra Treinamento: [172.1 57.94], Amostra Teste: [160.73 77.07]
Distância: 12.95, Amostra Treinamento: [172.1 57.94], Amostra Teste: [164.96 68.74]
Distância: 13.15, Amostra Treinamento: [172.1 57.94], Amostra Teste: [180.01 68.44]
Distância: 4.30, Amostra Treinamento: [172.1 57.94], Amostra Teste: [168.11 56.34]
Distância: 23.21, Amostra Treinamento: [172.1 57.94], Amostra Teste: [177.57 80.5]
Distância: 21.29, Amostra Treinamento: [172.1 57.94], Amostra Teste: [178.15 78.35]
Distância: 26.45, Amostra Treinamento: [172.1 57.94], Amostra Teste: [188.72 78.51]
Distância: 7.50, Amostra Treinamento: [172.1 57.94], Amostra Teste: [174.55 50.85]
Distância: 16.63, Amostra Treinamento: [172.1 57.94], Amostra Teste: [171.91 74.57]
Distância: 0.45, Amostra Treinamento: [172.1 57.94], Amostra Teste: [172.05 58.39]
Distância: 34.61, Amostra Treinamento: [172.1 57.94], Amostra Teste: [172.43 92.55]
Distância: 17.97, Amostra Treinamento: [172.1 57.94], Amostra Teste: [171.32 75.89]
Distância: 19.09, Amostra Treinamento: [172.1 57.94], Amostra Teste: [187.74 68.89]
Distância: 30.36, Amostra Treinamento: [177.15 92.69], Amostra Teste: [159.96 67.67]
Distância: 11.44, Amostra Treinamento: [177.15 92.69], Amostra Teste: [165.8 91.29]
Distância: 41.29, Amostra Treinamento: [177.15 92.69], Amostra Teste: [185.48 52.25]
Distância: 26.53, Amostra Treinamento: [177.15 92.69], Amostra Teste: [168.15 67.73]
Distância: 42.21, Amostra Treinamento: [177.15 92.69], Amostra Teste: [165.98 51.98]
Distância: 23.46, Amostra Treinamento: [177.15 92.69], Amostra Teste: [185.42 70.74]
Distância: 25.19, Amostra Treinamento: [177.15 92.69], Amostra Teste: [160.2 74.05]
Distância: 19.32, Amostra Treinamento: [177.15 92.69], Amostra Teste: [172.58 73.92]
Distância: 42.65, Amostra Treinamento: [177.15 92.69], Amostra Teste: [167.33 51.19]
Distância: 18.20, Amostra Treinamento: [177.15 92.69], Amostra Teste: [160.05 86.46]
Distância: 42.76, Amostra Treinamento: [177.15 92.69], Amostra Teste: [156.83 55.07]
Distância: 27.04, Amostra Treinamento: [177.15 92.69], Amostra Teste: [163.71 69.23]
Distância: 22.66, Amostra Treinamento: [177.15 92.69], Amostra Teste: [160.73 77.07]
Distância: 26.87, Amostra Treinamento: [177.15 92.69], Amostra Teste: [164.96 68.74]
Distância: 24.42, Amostra Treinamento: [177.15 92.69], Amostra Teste: [180.01 68.44]
Distância: 37.46, Amostra Treinamento: [177.15 92.69], Amostra Teste: [168.11 56.34]
Distância: 12.20, Amostra Treinamento: [177.15 92.69], Amostra Teste: [177.57 80.5]
Distância: 14.37, Amostra Treinamento: [177.15 92.69], Amostra Teste: [178.15 78.35]
Distância: 18.30, Amostra Treinamento: [177.15 92.69], Amostra Teste: [188.72 78.51]
Distância: 41.92, Amostra Treinamento: [177.15 92.69], Amostra Teste: [174.55 50.85]
Distância: 18.86, Amostra Treinamento: [177.15 92.69], Amostra Teste: [171.91 74.57]
Distância: 34.68, Amostra Treinamento: [177.15 92.69], Amostra Teste: [172.05 58.39]
Distância: 4.72, Amostra Treinamento: [177.15 92.69], Amostra Teste: [172.43 92.55]
Distância: 17.78, Amostra Treinamento: [177.15 92.69], Amostra Teste: [171.32 75.89]
Distância: 26.05, Amostra Treinamento: [177.15 92.69], Amostra Teste: [187.74 68.89]
Distância: 13.95, Amostra Treinamento: [154.78 80.62], Amostra Teste: [159.96 67.67]
Distância: 15.34, Amostra Treinamento: [154.78 80.62], Amostra Teste: [165.8 91.29]
Distância: 41.80, Amostra Treinamento: [154.78 80.62], Amostra Teste: [185.48 52.25]
Distância: 18.57, Amostra Treinamento: [154.78 80.62], Amostra Teste: [168.15 67.73]
Distância: 30.75, Amostra Treinamento: [154.78 80.62], Amostra Teste: [165.98 51.98]
Distância: 32.19, Amostra Treinamento: [154.78 80.62], Amostra Teste: [185.42 70.74]
Distância: 8.52, Amostra Treinamento: [154.78 80.62], Amostra Teste: [160.2 74.05]
Distância: 19.02, Amostra Treinamento: [154.78 80.62], Amostra Teste: [172.58 73.92]
Distância: 31.99, Amostra Treinamento: [154.78 80.62], Amostra Teste: [167.33 51.19]
Distância: 7.87, Amostra Treinamento: [154.78 80.62], Amostra Teste: [160.05 86.46]
Distância: 25.63, Amostra Treinamento: [154.78 80.62], Amostra Teste: [156.83 55.07]
Distância: 14.47, Amostra Treinamento: [154.78 80.62], Amostra Teste: [163.71 69.23]
Distância: 6.93, Amostra Treinamento: [154.78 80.62], Amostra Teste: [160.73 77.07]
Distância: 15.65, Amostra Treinamento: [154.78 80.62], Amostra Teste: [164.96 68.74]
Distância: 28.02, Amostra Treinamento: [154.78 80.62], Amostra Teste: [180.01 68.44]
Distância: 27.70, Amostra Treinamento: [154.78 80.62], Amostra Teste: [168.11 56.34]
Distância: 22.79, Amostra Treinamento: [154.78 80.62], Amostra Teste: [177.57 80.5]
Distância: 23.48, Amostra Treinamento: [154.78 80.62], Amostra Teste: [178.15 78.35]
Distância: 34.01, Amostra Treinamento: [154.78 80.62], Amostra Teste: [188.72 78.51]
Distância: 35.74, Amostra Treinamento: [154.78 80.62], Amostra Teste: [174.55 50.85]
Distância: 18.17, Amostra Treinamento: [154.78 80.62], Amostra Teste: [171.91 74.57]
Distância: 28.15, Amostra Treinamento: [154.78 80.62], Amostra Teste: [172.05 58.39]
Distância: 21.30, Amostra Treinamento: [154.78 80.62], Amostra Teste: [172.43 92.55]
Distância: 17.20, Amostra Treinamento: [154.78 80.62], Amostra Teste: [171.32 75.89]
Distância: 34.99, Amostra Treinamento: [154.78 80.62], Amostra Teste: [187.74 68.89]
Distância: 23.48, Amostra Treinamento: [165.57 90.47], Amostra Teste: [159.96 67.67]
Distância: 0.85, Amostra Treinamento: [165.57 90.47], Amostra Teste: [165.8 91.29]
Distância: 43.09, Amostra Treinamento: [165.57 90.47], Amostra Teste: [185.48 52.25]
Distância: 22.89, Amostra Treinamento: [165.57 90.47], Amostra Teste: [168.15 67.73]
Distância: 38.49, Amostra Treinamento: [165.57 90.47], Amostra Teste: [165.98 51.98]
Distância: 27.99, Amostra Treinamento: [165.57 90.47], Amostra Teste: [185.42 70.74]
Distância: 17.28, Amostra Treinamento: [165.57 90.47], Amostra Teste: [160.2 74.05]
Distância: 17.97, Amostra Treinamento: [165.57 90.47], Amostra Teste: [172.58 73.92]
Distância: 39.32, Amostra Treinamento: [165.57 90.47], Amostra Teste: [167.33 51.19]
Distância: 6.82, Amostra Treinamento: [165.57 90.47], Amostra Teste: [160.05 86.46]
Distância: 36.46, Amostra Treinamento: [165.57 90.47], Amostra Teste: [156.83 55.07]

In [ ]:
# Criando o classificador com k=1
knn = KNeighborsClassifier(n_neighbors=1)

# Treinando o modelo
knn.fit(X_train, y_train)

# Previsões para o conjunto de teste
y_pred = knn.predict(X_test)

In [ ]:
acuracia = accuracy_score(y_test, y_pred)
print(f'Acurácia: {acuracia}')

Acurácia: 0.9333333333333333

In [ ]:
distancias, indices = knn.kneighbors(X_test)

# Criando o DataFrame com os resultados
resultados = pd.DataFrame({
    'weight': X_test['weight'],
    'height': X_test['height'],
    'classe_real': y_test,
    'classe_predita': y_pred,
    'distancia': distancias[:, 0]  # Distância do vizinho mais próximo
})

print(resultados)

    weight  height  classe_real  classe_predita  distancia
13   68.74  164.96            0               0   1.342609
39   68.47  161.72            0               0   1.933287
30   56.76  169.66            0               0   1.605895
45   80.09  172.41            1               1   3.229675
17   78.35  178.15            1               1   2.226859
48   82.79  178.40            1               1   1.681071
26   88.52  148.45            1               1  10.123186
25   73.84  172.08            1               0   0.506360
32   92.69  177.15            1               1   3.070016
19   50.85  174.55            0               0   3.846895
12   77.07  160.73            0               0   3.066154
4    51.98  165.98            0               0   4.852474
37   72.17  173.80            0               0   2.133284
8    51.19  167.33            0               0   4.737193
3    67.73  168.15            0               0   4.686534